# Generated by Django 6.0.5 on 2026-05-19 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
                migrations.AddField(
                    model_name='client',
                    name='last_meeting_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='client',
                    name='last_message_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='client',
                    name='notes',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='client',
                    name='priority',
                    field=models.CharField(choices=[('vip', 'VIP'), ('premium', 'Premium'), ('regular', 'Regular')], default='regular', max_length=20),
                ),
                migrations.AddField(
                    model_name='client',
                    name='revenue_paid',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                migrations.AddField(
                    model_name='client',
                    name='revenue_pending',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                migrations.AddField(
                    model_name='client',
                    name='satisfaction',
                    field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='attachment',
                    field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='category',
                    field=models.CharField(choices=[('ui_design', 'UI Design'), ('bug', 'Bug'), ('performance', 'Performance'), ('communication', 'Communication'), ('feature_request', 'Feature Request')], default='ui_design', max_length=50),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='reply',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='status',
                    field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
                ),
                migrations.AddField(
                    model_name='message',
                    name='file',
                    field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='is_read',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='message',
                    name='content',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='task',
                    name='status',
                    field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Completed')], default='todo', max_length=20),
                ),
                migrations.CreateModel(
                    name='ActivityLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activity_type', models.CharField(max_length=100)),
                        ('description', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.client')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='ClientPermission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('can_upload', models.BooleanField(default=True)),
                        ('can_comment', models.BooleanField(default=True)),
                        ('can_edit', models.BooleanField(default=False)),
                        ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.client')),
                    ],
                ),
                migrations.CreateModel(
                    name='Invoice',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('invoice_number', models.CharField(max_length=50, unique=True)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20)),
                        ('due_date', models.DateField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.client')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project')),
                    ],
                ),
                migrations.CreateModel(
                    name='Meeting',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('start_time', models.DateTimeField()),
                        ('end_time', models.DateTimeField()),
                        ('description', models.TextField(blank=True, null=True)),
                        ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                        ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
                    ],
                ),
                migrations.CreateModel(
                    name='MeetingNote',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('summary', models.TextField()),
                        ('discussion_points', models.TextField()),
                        ('next_actions', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='projects.client')),
                    ],
                ),
                migrations.CreateModel(
                    name='TaskComment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('content', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task')),
                    ],
                ),
                migrations.CreateModel(
                    name='TaskFile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('file', models.FileField(upload_to='task_files/')),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.task')),
                    ],
                ),
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision requested')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('planning', 'Planning'), ('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('deployment', 'Deployment')], default='planning', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default='UI/UX, Django', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='worked_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
