# Generated by Django 6.0.5 on 2026-05-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_userprofile_is_frozen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video_url', models.URLField(blank=True, null=True)),
                ('demo_project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_urls', to='projects.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_urls', to='projects.project')),
            ],
        ),
    ]
