# Generated by Django 6.0.5 on 2026-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_userprofile_is_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
