# Generated by Django 5.2.11 on 2026-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_attendance_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
