# Generated by Django 6.0.5 on 2026-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
