# Generated by Django 6.0.5 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_demourl_advance_payment_demourl_full_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='demourl',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
