# Generated by Django 6.0.5 on 2026-05-24 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_userprofile_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='demo_videos/')),
                ('main_project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payment_type', models.CharField(choices=[('advance', 'Advance Payment'), ('full', 'Full Payment')], default='advance', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('pm_approved', 'Approved by PM'), ('client_approved', 'Approved by Client'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_submissions', to='projects.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_submissions', to='projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_demos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
