# Generated by Django 5.2.11 on 2026-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_demourl_status'),
        ('projects', '0016_demosubmission'),
    ]

    operations = [
    ]
