# Generated by Django 6.0.5 on 2026-06-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_merge_0015_demourl_status_0016_demosubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='report_files/'),
        ),
    ]
