# Generated by Django 5.2.11 on 2026-06-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_merge_20260617_0000'),
        ('projects', '0018_report_attachment'),
    ]

    operations = [
    ]
